// <auto-generated />
using System;
using APBD_11.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APBD_11.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200524163804_SeedPrescription_Medicaments")]
    partial class SeedPrescription_Medicaments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.4.20220.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APBD_11.Models.Doctor", b =>
                {
                    b.Property<int>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IdDoctor")
                        .HasName("Enrollment_pk");

                    b.ToTable("Doctor","apbd_doctor");

                    b.HasData(
                        new
                        {
                            IdDoctor = 1,
                            Email = "Frey@fray.com",
                            FirstName = "Jimmy",
                            LastName = "Frey"
                        },
                        new
                        {
                            IdDoctor = 2,
                            Email = "ONeill@oneil.com",
                            FirstName = "Erin",
                            LastName = "ONeill"
                        },
                        new
                        {
                            IdDoctor = 3,
                            Email = "Clements@clements.com",
                            FirstName = "Bobbie",
                            LastName = "Clements"
                        },
                        new
                        {
                            IdDoctor = 4,
                            Email = "Britton@britton.com",
                            FirstName = "Elena",
                            LastName = "Britton"
                        });
                });

            modelBuilder.Entity("APBD_11.Models.Medicament", b =>
                {
                    b.Property<int>("IdMedicament")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IdMedicament")
                        .HasName("Medicament_pk");

                    b.ToTable("Medicament","apbd_doctor");

                    b.HasData(
                        new
                        {
                            IdMedicament = 1,
                            Description = "desc_1",
                            Name = "med_1",
                            Type = "type_1"
                        },
                        new
                        {
                            IdMedicament = 2,
                            Description = "desc_2",
                            Name = "med_2",
                            Type = "type_2"
                        },
                        new
                        {
                            IdMedicament = 3,
                            Description = "desc_3",
                            Name = "med_3",
                            Type = "type_3"
                        },
                        new
                        {
                            IdMedicament = 4,
                            Description = "desc_4",
                            Name = "med_4",
                            Type = "type_4"
                        },
                        new
                        {
                            IdMedicament = 5,
                            Description = "desc_5",
                            Name = "med_5",
                            Type = "type_5"
                        },
                        new
                        {
                            IdMedicament = 6,
                            Description = "desc_6",
                            Name = "med_6",
                            Type = "type_6"
                        });
                });

            modelBuilder.Entity("APBD_11.Models.Patient", b =>
                {
                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IdPatient")
                        .HasName("Patient_pk");

                    b.ToTable("Patient","apbd_doctor");

                    b.HasData(
                        new
                        {
                            IdPatient = 1,
                            BirthDate = new DateTime(1980, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jan",
                            LastName = "Kowalczyk"
                        },
                        new
                        {
                            IdPatient = 2,
                            BirthDate = new DateTime(1986, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anna",
                            LastName = "Power"
                        },
                        new
                        {
                            IdPatient = 3,
                            BirthDate = new DateTime(1930, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Saxon",
                            LastName = "Beattie"
                        },
                        new
                        {
                            IdPatient = 4,
                            BirthDate = new DateTime(1992, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gia",
                            LastName = "Forrest"
                        });
                });

            modelBuilder.Entity("APBD_11.Models.Prescription", b =>
                {
                    b.Property<int>("IdPrescription")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.HasKey("IdPrescription")
                        .HasName("Prescription_pk");

                    b.HasIndex("IdDoctor");

                    b.HasIndex("IdPatient");

                    b.ToTable("Prescription","apbd_doctor");

                    b.HasData(
                        new
                        {
                            IdPrescription = 1,
                            Date = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 1,
                            IdPatient = 1
                        },
                        new
                        {
                            IdPrescription = 2,
                            Date = new DateTime(2020, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 1,
                            IdPatient = 1
                        },
                        new
                        {
                            IdPrescription = 3,
                            Date = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 2,
                            IdPatient = 1
                        },
                        new
                        {
                            IdPrescription = 4,
                            Date = new DateTime(2020, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 1,
                            IdPatient = 2
                        },
                        new
                        {
                            IdPrescription = 5,
                            Date = new DateTime(2020, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 3,
                            IdPatient = 2
                        },
                        new
                        {
                            IdPrescription = 6,
                            Date = new DateTime(2020, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 3,
                            IdPatient = 3
                        },
                        new
                        {
                            IdPrescription = 7,
                            Date = new DateTime(2020, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 2,
                            IdPatient = 3
                        },
                        new
                        {
                            IdPrescription = 8,
                            Date = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 1,
                            IdPatient = 4
                        },
                        new
                        {
                            IdPrescription = 10,
                            Date = new DateTime(2020, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 4,
                            IdPatient = 4
                        },
                        new
                        {
                            IdPrescription = 11,
                            Date = new DateTime(2020, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 4,
                            IdPatient = 4
                        });
                });

            modelBuilder.Entity("APBD_11.Models.Prescription_Medicament", b =>
                {
                    b.Property<int>("IdMedicament")
                        .HasColumnType("int");

                    b.Property<int>("IdPrescription")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("Dose")
                        .HasColumnType("int");

                    b.HasKey("IdMedicament", "IdPrescription");

                    b.HasIndex("IdPrescription");

                    b.ToTable("Prescription_Medicament","apbd_doctor");

                    b.HasData(
                        new
                        {
                            IdMedicament = 1,
                            IdPrescription = 1,
                            Details = "details 1",
                            Dose = 30
                        },
                        new
                        {
                            IdMedicament = 1,
                            IdPrescription = 2,
                            Details = "details 2",
                            Dose = 15
                        },
                        new
                        {
                            IdMedicament = 2,
                            IdPrescription = 3,
                            Details = "details 3",
                            Dose = 100
                        },
                        new
                        {
                            IdMedicament = 3,
                            IdPrescription = 4,
                            Details = "details 4",
                            Dose = 20
                        },
                        new
                        {
                            IdMedicament = 5,
                            IdPrescription = 6,
                            Details = "details 5",
                            Dose = 10
                        },
                        new
                        {
                            IdMedicament = 6,
                            IdPrescription = 7,
                            Details = "details 6",
                            Dose = 5
                        },
                        new
                        {
                            IdMedicament = 6,
                            IdPrescription = 8,
                            Details = "details 7",
                            Dose = 14
                        },
                        new
                        {
                            IdMedicament = 6,
                            IdPrescription = 9,
                            Details = "details 8",
                            Dose = 100
                        },
                        new
                        {
                            IdMedicament = 3,
                            IdPrescription = 10,
                            Details = "details 9",
                            Dose = 8
                        },
                        new
                        {
                            IdMedicament = 3,
                            IdPrescription = 5,
                            Details = "details 10",
                            Dose = 10
                        },
                        new
                        {
                            IdMedicament = 4,
                            IdPrescription = 2,
                            Details = "details 11",
                            Dose = 21
                        });
                });

            modelBuilder.Entity("APBD_11.Models.Prescription", b =>
                {
                    b.HasOne("APBD_11.Models.Doctor", "Doctor")
                        .WithMany("Prescription")
                        .HasForeignKey("IdDoctor")
                        .HasConstraintName("Doctor_Prescription")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_11.Models.Patient", "Patient")
                        .WithMany("Prescription")
                        .HasForeignKey("IdPatient")
                        .HasConstraintName("Patient_Prescription")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APBD_11.Models.Prescription_Medicament", b =>
                {
                    b.HasOne("APBD_11.Models.Medicament", "Medicament")
                        .WithMany("Prescription_Medicament")
                        .HasForeignKey("IdMedicament")
                        .HasConstraintName("Medicament_Prescription_Medicament")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_11.Models.Prescription", "Prescription")
                        .WithMany("Prescription_Medicament")
                        .HasForeignKey("IdPrescription")
                        .HasConstraintName("Prescription_Prescription_Medicament")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
